name: Cypress Tests with Allure

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust version if needed

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Allure
        run: npx cypress run --reporter mocha-allure-reporter

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: allure-report
