name: Cypress Test and Allure Report

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline
          echo "Allure CLI installed."

      - name: Run Cypress Tests with Allure
        if: always()
        continue-on-error: true
        run: |
          npx cypress run --browser chrome --headless --env allure=true
          echo "Cypress tests executed with Allure reporting."

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        id: build
        uses: simple-elf/allure-report-action@master
        if: always()
        continue-on-error: true
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Wait for Allure report to be generated
        if: always()
        continue-on-error: true
        run: sleep 10

      - name: Update Allure Report Widget Title
        continue-on-error: true
        if: steps.build.outcome == 'success'
        run: |
          latest_folder=$(find allure-history -mindepth 1 -maxdepth 1 -type d -name '[0-9]*' | sort -n | tail -n 1)
          echo "Latest Folder: $latest_folder"
          summary_path="$latest_folder/widgets/summary.json"
          echo "Summary Path: $summary_path"

          if [[ -e "$summary_path" ]]; then
            cat "$summary_path"  # Print content before
            sudo sed -i 's/Allure Report/Cypress - UI Test Results/' "$summary_path"
            cat "$summary_path"  # Print content after
          else
            echo "Error: summary.json not found in the latest folder."
          fi

      - name: Deploy report to GitHub Pages
        id: deploy
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
